### ISSUE TITLE
`@dynamic [dict_type] ...` notation for optional constant time dynamic property look-up

### ISSUE THREAD

**Issue by AntonOresten** [AntonOresten/DynamicStructs.jl#13]
The dynamic macro could possibly take an optional `dict_type` argument, that gets propagated further down the chain, i.e. `DynamicProperties{D<:AbstractDict{Symbol,Any}}`.

```julia
julia> @dynamic OrderedDict{Symbol,Any} struct LargeSpaceship
           name::String
       end

julia> @dynamic LittleDict{Symbol,Any} struct LittleSpaceship
           name::String
       end

julia> @dynamic struct DefaultSpaceship # uses LittleDict{Symbol,Any} by default
           name::String
       end
```

where OrderedDict would be meant for structs expected to have a lot of properties, but this might be an unlikely use-case since dynamic structs are mostly for convenience to users, and it's hard to imagine users realistically using hundreds of properties.

**Comment by ameligrana** [comment]
yes, to me this seems a bit outside the use-case of dynamic structs, and I think that `LittleDict` already offers what's best for the library
