### ISSUE TITLE
Add function to check if type is dynamic

### ISSUE THREAD

**Issue by ameligrana** [AntonOresten/DynamicStructs.jl#3]
something like `isdynamic` or `isdynamicstruct` could be useful for some reflection tasks

**Comment by AntonOresten** [comment]
Great suggestion!

The functions `isdynamictype` and `isdynamic` have been added, and should be in 0.1.0, which is hopefully being added in General soon!😄

I'm following the design of e.g. Base's `isbitstype` and `isbits`, `ismutabletype` and `ismutable` from [reflection.jl](https://github.com/JuliaLang/julia/blob/master/base/reflection.jl). The only thing I noticed is that `ismutable` returns true even when passing the mutable struct type itself. In this regard, `isdynamic` works more like `isbits`, in that, `isbits(Int)` is false, while `isbits(1)` is true.

EDIT: nvm, they explain the behavior of `ismutable` in the docstring, and even immutable struct types are intended to return `true` when passed to `ismutable`.
