### ISSUE TITLE
Storing properties: `OrderedDict` vs `Dict` vs something else?

### ISSUE THREAD

**Issue by AntonOresten** [AntonOresten/DynamicStructs.jl#9]
Dictionaries are comparatively slow for small N. The package could potentially become a lot faster (for small N) by doing linear searches through some vector of pairs. It's also worth comparing `OrderedDict`s to regular `Dict`s (instead storing names in a vector to keep track of order? Is consistent order unnecessary?).

**Comment by ameligrana** [comment]
Also worth considering `OrderedDict.LittleDict`. I would say that consistent order is good because I would like a consistent order in `propertynames`

**Comment by AntonOresten** [comment]
Hm... `LittleDict` looks like a good fit. Certainly better than a vector.

**Comment by ameligrana** [comment]
Actually thinking about it, the order is not necessary to be maintained, because two different dynamic structs with the same properties could have those properties in different order because actually the maintained order is the insertion one. So a `Dict` might also be good in my opinion.

**Comment by AntonOresten** [comment]
`LittleDict` is not... slower, at least. There was kinda high variance between runs so take it with a grain of salt. I think the main problem is just the unknown size and unpredictability of the type.
```julia
julia> @benchmark $(a).y # dynamic property of dynamic struct with OrderedDict
BenchmarkTools.Trial: 10000 samples with 998 evaluations.
 Range (min … max):  12.926 ns … 56.613 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     13.226 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   13.297 ns ±  0.525 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

           █  ▂
  ▃▁▁▃▁▁▆▁▁█▁▁█▁▁▃▁▁▄▁▁▃▁▁▂▁▁▂▁▁▁▂▁▁▂▁▁▂▁▁▂▁▁▂▁▁▂▁▁▂▁▁▂▁▁▂▁▁▂ ▂
  12.9 ns         Histogram: frequency by time        14.8 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

julia> @benchmark $(b).y # dynamic property of dynamic struct with LittleDict
BenchmarkTools.Trial: 10000 samples with 999 evaluations.
 Range (min … max):  11.712 ns … 71.572 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     12.112 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   13.647 ns ±  3.080 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

  ▅█▃▁▃▂▃▂▁▂▂▃▂▂▂▄▃                                           ▁
  █████████████████▆▅▆▄▆▆▅▅▅▅▅▅▄▆▅▇▆▇▆▇█▇█▇▆▆▇▆▆▅▅▅▅▄▅▆▃▅▅▃▄▃ █
  11.7 ns      Histogram: log(frequency) by time      27.4 ns <

 Memory estimate: 0 bytes, allocs estimate: 0
```

Should still make the memory footprint smaller, and maybe make #10 less of a problem (although lazy initialization of dicts are a good idea).
